[theme]
# Bright blue for interactive elements (lighter than before for better contrast)
primaryColor = "#4dabf7"
# Dark grey-blue background color
backgroundColor = "#2a2d3e"
# Slightly darker grey-blue for containers
secondaryBackgroundColor = "#1e2132"
# White text for better contrast
textColor = "#ffffff"
# Font family for all text
font = "sans serif"

[server]
# Prevents other websites from making requests to this app
enableCORS = false
# Adds security tokens to forms to prevent unauthorized access
enableXsrfProtection = true
